name: flutter_calculator_example
description: The flutter calculator example
version: 0.1.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_calculator:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  # https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: ^0.7.4

flutter:
  uses-material-design: true

# Run `flutter pub run flutter_launcher_icons:main` to update launcher icon
# https://github.com/fluttercommunity/flutter_launcher_icons/blob/master/example/pubspec.yaml#L19
flutter_icons:
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  image_path: "../assets/images/icon.png"
